export { CreateATCHarness, type CreateATCHarnessDependencies } from './app/CreateATCHarness.js';
export { parseCreateATCHarnessCommandLine } from './cli/parseCommandLine.js';
export { runCreateATCHarnessCLI } from './cli/runCreateATCHarness.js';
export type { CommandLineOptions } from './domain/CommandLineOptions.js';
export { HarnessCreationResult, HarnessResultState } from './domain/HarnessCreationResult.js';
export { HarnessCreationSettings, type HarnessCreationSettingsInit } from './domain/HarnessCreationSettings.js';
export type { LiveStatusHandle } from './domain/LiveStatusHandle.js';
export { EngineTemplateHarnessCreator } from './harness/EngineTemplateHarnessCreator.js';
export { GitHarnessCreator } from './harness/GitHarnessCreator.js';
export { Harness } from './harness/Harness.js';
export type { HarnessCreator } from './harness/HarnessCreator.js';
export type { ATCManifest } from './manifest/ATCManifest.js';
export { parseAndValidateATCManifest } from './manifest/ATCManifest.js';
export { GitManifestSource } from './manifest/GitManifestSource.js';
export { LocalPathManifestSource } from './manifest/LocalPathManifestSource.js';
export type { ManifestResolution, ManifestResolutionContext, ManifestSource } from './manifest/ManifestSource.js';
export { EngineDirectoryResolver, type ResolvedEngineContext } from './services/EngineDirectoryResolver.js';
export type { FileSystem } from './services/FileSystem.js';
export type { GitService } from './services/GitService.js';
export { SimpleGitService } from './services/GitService.js';
export { isGitLikeReference, type ParsedGitReference, parseGitReference } from './services/GitUrl.js';
export { NodeFileSystem } from './services/NodeFileSystem.js';
export { OutputDirectoryGuard } from './services/OutputDirectoryGuard.js';
