#!/usr/bin/env sh
set +e

pnpm format:check
FORMAT_STATUS=$?

if [ $FORMAT_STATUS -ne 0 ]; then
  echo ""
  echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
  echo "❌ Formatting check failed"
  echo "👉 Run: pnpm format"
  echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
  exit 1;
fi

pnpm lint
LINT_STATUS=$?
if [ $LINT_STATUS -ne 0 ]; then
  echo ""
  echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
  echo "❌ Lint failed"
  echo "👉 Run: pnpm lint --fix"
  echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
  exit 1;
fi
